name: Deploy to Base

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Compile contracts
      run: npx hardhat compile

    - name: Run tests
      run: npm test

  deploy-sepolia:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Deploy to Base Sepolia
      run: npx hardhat run scripts/deploy-erc20.js --network baseSepolia
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        BASESCAN_API_KEY: ${{ secrets.BASESCAN_API_KEY }}

  deploy-mainnet:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push' && contains(github.event.head_commit.message, '[deploy-mainnet]')

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Deploy to Base Mainnet
      run: npx hardhat run scripts/deploy-erc20.js --network baseMainnet
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        BASESCAN_API_KEY: ${{ secrets.BASESCAN_API_KEY }}